import { SITE } from "./config.js";

const root = document.getElementById("app");
const base = location.pathname.startsWith("/Ventro-Bank-Website") ? "/Ventro-Bank-Website" : "";
const path = (location.pathname.startsWith(base) ? location.pathname.slice(base.length) : location.pathname).replace(/\/$/, "") || "/";
const link = p => base + (p === "/" ? "/" : p);
const logo = `${base}/assets/ventro-mark.svg`;
const preview = `${base}/assets/app-preview.svg`;
const api = SITE.backendApiUrl?.replace(/\/$/, "");

const features = [
 ["01","FICTIONAL BALANCE","Track a custom fictional balance inside the simulator."],["02","EARN","Add roleplay income and build your fictional financial story."],["03","SPEND","Generate fictional purchases across luxury categories."],["04","TRANSACTION HISTORY","Review generated activity in a structured history."],["05","NET WORTH","Combine your fictional balance and assets."],["06","LUXURY ASSETS","Collect cars, watches, jewelry, homes, yachts and more."],["07","VAULT","Progress through vault levels and milestones."],["08","ACHIEVEMENTS","Unlock simulator achievements."],["09","STATISTICS","View fictional financial activity at a glance."],["10","PROFILE","Customize your in-app identity."],["11","CUSTOMIZATION","Tune your Ventro experience."],["12","NOTIFICATIONS","Stay informed about simulator activity and milestones."],["13","LARP ROLEPLAY","Built for fictional banking scenarios and entertainment."]
];

function header(){return `<div class="topline"></div><header><div class="shell nav"><a class="brand" href="${link("/")}"><img src="${logo}" alt="Ventro Bank"><span>VENTRO BANK</span></a><button class="mobile-menu" aria-label="Open menu" onclick="document.querySelector('.navlinks').classList.toggle('open')">MENU</button><nav class="navlinks">${[["/store","STORE"],["/features","FEATURES"],["/app","APP"],["/updates","UPDATES"],["/community","COMMUNITY"],["/faq","FAQ"],["/support","SUPPORT"],["/account","ACCOUNT"]].map(([p,t])=>`<a href="${link(p)}">${t}</a>`).join("")}</nav></div></header>`}
function footer(){return `<footer><div class="shell footer-grid"><div><div class="brand"><img src="${logo}" alt="Ventro Bank"><span>VENTRO BANK</span></div><p class="muted">${SITE.tagline}</p><span class="status">FICTIONAL · LARP</span></div><div><div class="footer-title">Product</div><a href="${link("/store")}">Store</a><a href="${link("/features")}">Features</a><a href="${link("/app")}">App</a><a href="${link("/updates")}">Updates</a></div><div><div class="footer-title">Account</div><a href="${link("/login")}">Log In</a><a href="${link("/signup")}">Sign Up</a><a href="${link("/downloads")}">Downloads</a><a href="${link("/subscription")}">Updates Subscription</a></div><div><div class="footer-title">Legal & Support</div><a href="${link("/privacy")}">Privacy Policy</a><a href="${link("/terms")}">Terms</a><a href="${link("/disclaimer")}">Disclaimer</a><a href="${link("/data-deletion")}">Data Deletion</a><a href="${link("/app-support")}">App Support</a></div></div><div class="shell fineprint"><span>© ${new Date().getFullYear()} Ventro Bank</span><span>Ventro Bank is a fictional banking simulator designed for LARP, roleplay, and entertainment. It does not provide real banking or financial services.</span></div></footer>`}
function layout(content){root.innerHTML=header()+`<main>${content}</main>`+footer();window.scrollTo(0,0)}
function head(k,t,d){return `<div class="page-head"><div class="eyebrow">${k}</div><h1 class="page-title">${t}</h1><p class="lead">${d}</p></div>`}
function formBox(title,body){return `<div class="form-box"><h2>${title}</h2>${body}</div>`}
async function request(pathname, options={}){if(!api) throw new Error("The secure backend has not been configured yet."); const r=await fetch(`${api}${pathname}`,{credentials:"include",...options,headers:{"content-type":"application/json",...(options.headers||{})}}); const data=await r.json().catch(()=>({})); if(!r.ok) throw new Error(data.error||"Request failed."); return data;}
function errorBox(e){return `<div class="notice error">${e?.message||e}</div>`}
function home(){layout(`<section class="shell hero"><div><div class="eyebrow">FICTIONAL · LARP · ENTERTAINMENT</div><h1>VENTRO <span>BANK</span></h1><h2>${SITE.tagline}</h2><p>A premium fictional banking simulator designed for LARP, roleplay, and entertainment. The app uses fictional money only.</p><div class="actions"><a class="btn primary" href="${link("/store")}">BUY VENTRO BANK · CA$10</a><a class="btn secondary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN DISCORD ↗</a></div><div class="notice"><strong>FICTIONAL · LARP</strong><br><span class="muted">Not a bank. No real deposits, withdrawals, loans, investments, transfers, or financial services.</span></div></div><div class="phone-wrap"><div class="phone"><img class="screen-image" src="${preview}" alt="Ventro Bank app dashboard"></div></div></section><section class="section alt"><div class="shell"><div class="section-head"><div><div class="eyebrow">SYSTEM OVERVIEW</div><h2>Everything in one vault.</h2></div><a class="btn secondary" href="${link("/features")}">VIEW FEATURES</a></div><div class="grid">${features.slice(0,6).map(f=>`<article class="card"><div class="num">${f[0]}</div><h3>${f[1]}</h3><p>${f[2]}</p></article>`).join("")}</div></div></section>`)}
function store(){layout(`<section class="page shell">${head("VENTRO STORE","Ventro Bank for CA$10.","One purchase. The complete fictional simulator is included. No additional app purchase is required.")}<div class="store-grid"><div class="cta"><span class="status">ONE-TIME PURCHASE</span><h2>Ventro Bank</h2><div class="price">CA$10</div><p class="lead">Purchase access through secure Stripe Checkout. After Stripe confirms payment server-side, your account receives download entitlement.</p><div id="store-action"><a class="btn primary" href="${link("/signup")}">CREATE ACCOUNT TO BUY</a></div></div><div class="card"><h3>Included</h3><p>Full Ventro Bank APK access after verified purchase.</p><p>All normal simulator functionality is included.</p><p>No real money or real financial services.</p><p>Future app releases can be delivered to eligible purchasers.</p></div></div></section>`); loadStoreState();}
async function loadStoreState(){const el=document.getElementById("store-action"); if(!el||!api)return; try{const me=await request("/auth/me"); if(me.user) el.innerHTML=`<button class="btn primary" id="buy-btn">BUY VENTRO BANK · CA$10</button>`; const b=document.getElementById("buy-btn"); if(b)b.onclick=async()=>{b.disabled=true;b.textContent="OPENING STRIPE...";try{const r=await request("/stripe/checkout",{method:"POST",body:"{}"});location.href=r.url}catch(e){el.insertAdjacentHTML("beforeend",errorBox(e));b.disabled=false;b.textContent="BUY VENTRO BANK · CA$10";}};}catch{}}
function featuresPage(){layout(`<section class="page shell">${head("VENTRO SYSTEMS","Built for fictional finance.","Explore the simulator systems that make Ventro Bank a structured LARP and roleplay experience.")}<div class="grid">${features.map(f=>`<article class="card"><div class="num">${f[0]}</div><div class="feature-icon">◈</div><h3>${f[1]}</h3><p>${f[2]}</p></article>`).join("")}</div></section>`)}
function appPage(){layout(`<section class="page shell">${head("THE APP","Your fictional vault.","A premium mobile-first simulator interface for fictional balances, assets, transactions, achievements, and roleplay.")}<div class="showcase">${["Dashboard","Transactions","Vault","Statistics","Profile","Achievements"].map(x=>`<figure class="shot"><div class="shot-screen"><img src="${preview}" alt="Ventro Bank ${x} app preview"></div><figcaption>${x}</figcaption></figure>`).join("")}</div><div class="notice"><strong>Current app preview.</strong> Additional real screenshots can replace these local assets later.</div></section>`)}
async function updates(){layout(`<section class="page shell">${head("UPDATES","Product updates.","Public Ventro Bank news and release notes.")}<div id="updates-list"><div class="notice">Loading updates...</div></div></section>`); const el=document.getElementById("updates-list"); if(!api){el.innerHTML=`<div class="list"><div class="row"><span class="check">●</span><div><strong>Independent website architecture</strong><br><span class="muted">GitHub Pages-ready frontend with a separate secure backend architecture.</span></div></div></div>`;return;} try{const r=await request("/updates");el.innerHTML=r.updates.length?r.updates.map(u=>`<article class="card"><div class="eyebrow">VERSION ${u.version} · ${new Date(u.published_at).toLocaleDateString()}</div><h2>${u.title}</h2><p>${u.description||""}</p><pre>${u.release_notes||""}</pre></article>`).join(""):"<div class='notice'>No updates published yet.</div>";}catch(e){el.innerHTML=errorBox(e)}}
function community(){layout(`<section class="page shell">${head("OFFICIAL COMMUNITY","Enter the Ventro vault.","Announcements, technical help, bug reports, and community discussion are handled through the official Discord.")}<div class="cta"><div class="status">OFFICIAL DISCORD</div><h2>Ventro Bank Community</h2><p class="lead">Join the official community for Ventro Bank support and updates.</p><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN DISCORD ↗</a></div></section>`)}
function faq(){layout(`<section class="page shell">${head("FAQ","Frequently asked questions.","Straight answers about Ventro Bank and the purchase system.")}<div class="faq"><details open><summary>Is Ventro Bank a real bank?</summary><p>No. It is a fictional LARP banking simulator for entertainment and roleplay.</p></details><details><summary>What does CA$10 buy?</summary><p>The one-time purchase grants access to download the Ventro Bank APK. The APK itself does not require another purchase.</p></details><details><summary>Does Ventro Bank handle real money?</summary><p>No. It does not provide deposits, withdrawals, loans, investments, transfers, or other real financial services.</p></details><details><summary>How is download access granted?</summary><p>Only a verified Stripe webhook can grant purchase entitlement to an account. The frontend cannot unlock a purchase by itself.</p></details><details><summary>Where is support?</summary><p>Support, bug reports, and technical assistance are handled through the official Discord community.</p></details></div></section>`)}
function support(){layout(`<section class="page shell">${head("SUPPORT","Need help with Ventro Bank?","All Ventro Bank support, technical assistance, bug reports, and help are handled through our official Discord community.")}<div class="cta"><h2>Official support channel</h2><p class="lead">There is no fake support ticket system on this website.</p><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN THE VENTRO BANK DISCORD ↗</a></div></section>`)}
function authPage(mode){const signup=mode==="signup"; layout(`<section class="page shell narrow">${head(signup?"ACCOUNT":"SECURE ACCESS",signup?"Create your Ventro Bank account.":"Log in to Ventro Bank.",signup?"An account is required before purchasing and accessing protected downloads.":"Use your Ventro Bank account to manage purchases and downloads.")}${formBox(signup?"Sign Up":"Log In",`<form id="auth-form"><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Password<input name="password" type="password" minlength="10" autocomplete="${signup?"new-password":"current-password"}" required></label><button class="btn primary" type="submit">${signup?"CREATE ACCOUNT":"LOG IN"}</button></form><div id="auth-message"></div><p class="muted">${signup?`Already have an account? <a href="${link("/login")}">Log in</a>`:`Need an account? <a href="${link("/signup")}">Sign up</a> · <a href="${link("/forgot-password")}">Forgot password?</a>`}</p>`)} </section>`);document.getElementById("auth-form").onsubmit=async e=>{e.preventDefault();const msg=document.getElementById("auth-message");msg.innerHTML="";const f=new FormData(e.currentTarget);try{await request(`/auth/${signup?"signup":"login"}`,{method:"POST",body:JSON.stringify({email:f.get("email"),password:f.get("password")})});location.href=link("/account");}catch(err){msg.innerHTML=errorBox(err)}}}
function forgot(){layout(`<section class="page shell narrow">${head("ACCOUNT RECOVERY","Reset your password.","If an account exists, the secure backend will send a password reset email.")}${formBox("Forgot Password",`<form id="forgot-form"><label>Email<input name="email" type="email" required></label><button class="btn primary">SEND RESET EMAIL</button></form><div id="forgot-message"></div>`)} </section>`);document.getElementById("forgot-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),m=document.getElementById("forgot-message");try{await request("/auth/forgot",{method:"POST",body:JSON.stringify({email:f.get("email")})});m.innerHTML='<div class="notice">If the account exists, a reset email has been sent.</div>'}catch(err){m.innerHTML=errorBox(err)}}}
function reset(){const token=new URLSearchParams(location.search).get("token")||"";layout(`<section class="page shell narrow">${head("ACCOUNT RECOVERY","Choose a new password.","Reset links expire and can only be used once.")}${formBox("New Password",`<form id="reset-form"><label>New password<input name="password" type="password" minlength="10" required></label><button class="btn primary">RESET PASSWORD</button></form><div id="reset-message"></div>`)} </section>`);document.getElementById("reset-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),m=document.getElementById("reset-message");try{await request("/auth/reset",{method:"POST",body:JSON.stringify({token,password:f.get("password")})});m.innerHTML=`<div class="notice">Password reset. <a href="${link("/login")}">Log in</a>.</div>`}catch(err){m.innerHTML=errorBox(err)}}}
async function account(){layout(`<section class="page shell">${head("ACCOUNT","Your Ventro Bank account.","Manage your purchase status, download access, and update subscription.")}<div id="account-content"><div class="notice">Checking secure account session...</div></div></section>`);const el=document.getElementById("account-content");if(!api){el.innerHTML=errorBox({message:"Secure backend not configured yet. Account features remain disabled until the Cloudflare Worker is deployed."});return;}try{const me=await request("/auth/me");if(!me.user){el.innerHTML=`<div class="cta"><h2>Log in required</h2><a class="btn primary" href="${link("/login")}">LOG IN</a><a class="btn secondary" href="${link("/signup")}">CREATE ACCOUNT</a></div>`;return;}const a=await request("/account");el.innerHTML=`<div class="grid"><div class="card"><div class="eyebrow">ACCOUNT</div><h3>${a.user.email}</h3><p>Created ${new Date(a.user.created_at).toLocaleDateString()}</p><button class="btn secondary" id="logout">LOG OUT</button></div><div class="card"><div class="eyebrow">PURCHASE</div><h3>${a.purchase?"PURCHASE VERIFIED":"NOT PURCHASED"}</h3><p>${a.purchase?`CA$${(a.purchase.amount/100).toFixed(2)} · ${new Date(a.purchase.purchased_at).toLocaleDateString()}`:"Purchase Ventro Bank to unlock protected downloads."}</p><a class="btn primary" href="${link(a.purchase?"/downloads":"/store")}">${a.purchase?"VIEW DOWNLOADS":"BUY VENTRO BANK · CA$10"}</a></div><div class="card"><div class="eyebrow">UPDATES</div><h3>${a.subscription?.status||"NOT SUBSCRIBED"}</h3><p>Optional email notifications for new Ventro Bank updates.</p><a class="btn secondary" href="${link("/subscription")}">MANAGE SUBSCRIPTION</a></div></div>`;document.getElementById("logout").onclick=async()=>{await request("/auth/logout",{method:"POST",body:"{}"});location.href=link("/")};}catch(e){el.innerHTML=errorBox(e)}}
async function downloads(){layout(`<section class="page shell">${head("PROTECTED DOWNLOADS","Ventro Bank downloads.","APK access is granted only after a verified purchase on your account.")}<div id="download-list"><div class="notice">Checking purchase entitlement...</div></div></section>`);const el=document.getElementById("download-list");if(!api){el.innerHTML=errorBox({message:"Secure backend not configured yet."});return;}try{const me=await request("/auth/me");if(!me.user){el.innerHTML=`<div class="notice">Please <a href="${link("/login")}">log in</a> to check download access.</div>`;return;}const r=await request("/releases");if(!r.purchased){el.innerHTML=`<div class="cta"><h2>Purchase required</h2><p class="lead">A verified CA$10 purchase is required before any APK download is exposed.</p><a class="btn primary" href="${link("/store")}">BUY VENTRO BANK · CA$10</a></div>`;return;}el.innerHTML=r.releases.length?r.releases.map(x=>`<article class="card release"><div class="eyebrow">VERSION ${x.version}</div><h2>${x.title}</h2><p>${x.description||""}</p><pre>${x.release_notes||""}</pre><a class="btn primary" href="${api}/download/${encodeURIComponent(x.id)}">DOWNLOAD APK</a></article>`).join(""):"<div class='notice'>Your purchase is verified, but no release has been published yet.</div>";}catch(e){el.innerHTML=errorBox(e)}}
async function subscription(){layout(`<section class="page shell">${head("VENTRO BANK UPDATES","Optional update notifications.","Subscribe separately if you want email notifications when new Ventro Bank updates are published.")}<div class="cta"><h2>Ventro Bank Updates</h2><p class="lead">This subscription is separate from the CA$10 app purchase. Stripe handles billing and the Customer Portal handles cancellation and management.</p><button class="btn primary" id="sub-buy">SUBSCRIBE FOR UPDATES</button><button class="btn secondary" id="sub-manage">MANAGE SUBSCRIPTION</button><div id="sub-msg"></div></div></section>`);const msg=document.getElementById("sub-msg");if(!api){msg.innerHTML=errorBox({message:"Secure backend not configured yet."});return;}for(const [id,path] of [["sub-buy","/subscription/checkout"],["sub-manage","/subscription/portal"]])document.getElementById(id).onclick=async()=>{try{const r=await request(path,{method:"POST",body:"{}"});location.href=r.url}catch(e){msg.innerHTML=errorBox(e)}}}
function admin(){layout(`<section class="page shell">${head("ADMIN","Ventro Bank administration.","Server-side authorization is required. The public frontend never decides who is an administrator.")}<div id="admin-content"><div class="notice">Checking authorization...</div></div></section>`);loadAdmin()}
async function loadAdmin(){const el=document.getElementById("admin-content");if(!api){el.innerHTML=errorBox({message:"Secure backend not configured yet."});return;}try{const o=await request("/admin/overview");el.innerHTML=`<div class="grid"><div class="card"><div class="eyebrow">USERS</div><h2>${o.users}</h2></div><div class="card"><div class="eyebrow">PURCHASES</div><h2>${o.purchases}</h2></div><div class="card"><div class="eyebrow">ACTIVE SUBSCRIPTIONS</div><h2>${o.activeSubscriptions}</h2></div><div class="card"><div class="eyebrow">LATEST VERSION</div><h2>${o.latest?.version||"None"}</h2></div></div><div class="notice"><strong>Release publishing</strong><p class="muted">APK files must be uploaded through the authenticated backend to protected R2 storage. Never place an unrestricted APK URL in the frontend.</p></div>`}catch(e){el.innerHTML=errorBox(e)}}
function legal(t,b){layout(`<section class="page shell legal">${head("LEGAL",t,"Last Updated: September 28, 2026")}<div class="notice">Ventro Bank is a fictional banking simulator designed for LARP, roleplay, and entertainment. It is not a bank and does not provide real banking or financial services.</div>${b}</section>`)}
function privacy(){legal("Privacy Policy",`<h2>Website and account system</h2><p>When the secure account system is deployed, Ventro Bank will process the email address and password credential needed to create and authenticate an account, plus account, purchase, subscription, and download entitlement records.</p><h2>Payments</h2><p>Stripe handles payment information. Ventro Bank does not store card numbers or security codes.</p><h2>Support and updates</h2><p>If you opt into Ventro Bank Updates, your subscription status and email address are used to send product update emails through a transactional email provider.</p><h2>Fictional banking data</h2><p>Simulator balances, assets, and transactions are fictional. Ventro Bank does not request bank account credentials, SIN, or government ID for the simulator.</p><h2>Third parties</h2><p>Stripe, the transactional email provider, Cloudflare, Google Play, and Discord may process information according to their own terms and privacy policies when you use those services.</p>`)}
function terms(){legal("Terms of Use",`<h2>Fictional product</h2><p>Ventro Bank is a fictional LARP banking simulator. It is not a bank or financial institution.</p><h2>Purchase</h2><p>The website may sell one-time access to the Ventro Bank APK for CA$10 through Stripe. Access is granted only after server-side payment verification.</p><h2>Downloads</h2><p>Protected APK releases are available to eligible purchased accounts. Sharing, redistributing, or attempting to bypass access controls is not authorized.</p><h2>No financial services</h2><p>Ventro Bank does not provide deposits, withdrawals, loans, investments, transfers, or other real financial services.</p>`)}
function disclaimer(){legal("Disclaimer",`<h2>Fictional</h2><p>Ventro Bank uses fictional money only and is designed for LARP, roleplay, and entertainment.</p><h2>No real financial activity</h2><p>Nothing in Ventro Bank represents a real account balance, asset value, deposit, withdrawal, transfer, investment, loan, or financial service.</p>`)}
function deletion(){legal("Data Deletion",`<h2>Account deletion</h2><p>When the secure backend is deployed, account deletion should be handled through the authenticated account workflow or official support if self-service deletion is not yet enabled.</p><h2>Payment records</h2><p>Payment and transaction records required for accounting, fraud prevention, or legal obligations may be retained as required by the relevant service providers and applicable law.</p><h2>Request help</h2><p>For deletion requests or questions, use the official Ventro Bank Discord support community.</p><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">CONTACT SUPPORT ON DISCORD ↗</a>`)}
function appSupport(){layout(`<section class="page shell">${head("GOOGLE PLAY SUPPORT","Ventro Bank app support.","Technical assistance, bug reports, and help are handled through the official Discord community.")}<div class="notice"><strong>Support channel:</strong><p class="muted">All Ventro Bank support, technical assistance, bug reports, and help are handled through our official Discord community.</p></div><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN THE VENTRO BANK DISCORD ↗</a></section>`)}
const routes={"/":home,"/store":store,"/features":featuresPage,"/app":appPage,"/updates":updates,"/community":community,"/faq":faq,"/support":support,"/login":()=>authPage("login"),"/signup":()=>authPage("signup"),"/forgot-password":forgot,"/reset-password":reset,"/account":account,"/downloads":downloads,"/subscription":subscription,"/admin":admin,"/privacy":privacy,"/terms":terms,"/disclaimer":disclaimer,"/data-deletion":deletion,"/app-support":appSupport};
(routes[path]||home)();
