import { SITE } from "./config.js";

const root = document.getElementById("app");
const path = window.location.pathname.replace(/\/$/,"") || "/";
const base = window.location.pathname.startsWith("/Ventro-Bank-Website") ? "/Ventro-Bank-Website" : "";
const link = p => base + (p === "/" ? "/" : p);

const features = [
["01","FICTIONAL BALANCE","Track a custom fictional balance inside the simulator."],
["02","EARN","Add roleplay income and build your in-app financial story."],
["03","SPEND","Generate fictional purchases across luxury categories."],
["04","TRANSACTIONS","Review generated activity in a structured history."],
["05","NET WORTH","Combine your fictional balance and assets."],
["06","LUXURY ASSETS","Collect cars, watches, jewelry, homes, yachts and more."],
["07","VAULT","Progress through vault levels and milestones."],
["08","ACHIEVEMENTS","Unlock simulator achievements as you play."],
["09","STATISTICS","View your fictional financial activity at a glance."],
["10","PROFILE","Customize your in-app identity and profile presentation."],
["11","CUSTOMIZATION","Tune the presentation of your Ventro experience."],
["12","LARP ROLEPLAY","Built around fictional banking scenarios and entertainment."]
];

function header(){return `<div class="topline"></div><header><div class="shell nav"><a class="brand" href="${link("/")}"><img src="${base}/assets/ventro-mark.svg" alt=""><span>VENTRO BANK</span></a><button class="mobile-menu" aria-label="Open menu" onclick="document.querySelector('.navlinks').classList.toggle('open')">MENU</button><nav class="navlinks">${["/features","/app","/updates","/community","/faq","/support"].map(p=>`<a href="${link(p)}">${p.slice(1).toUpperCase()}</a>`).join("")}</nav></div></header>`}

function footer(){return `<footer><div class="shell footer-grid"><div><div class="brand"><img src="${base}/assets/ventro-mark.svg" alt=""><span>VENTRO BANK</span></div><p class="muted">${SITE.tagline}</p><span class="status">FICTIONAL · LARP</span></div><div><div class="footer-title">Product</div><a href="${link("/features")}">Features</a><a href="${link("/app")}">App</a><a href="${link("/updates")}">Updates</a></div><div><div class="footer-title">Community</div><a href="${link("/community")}">Community</a><a href="${SITE.discordUrl}" target="_blank" rel="noopener">Discord</a><a href="${link("/support")}">Support</a><a href="${link("/faq")}">FAQ</a></div><div><div class="footer-title">Legal</div><a href="${link("/privacy")}">Privacy</a><a href="${link("/terms")}">Terms</a><a href="${link("/disclaimer")}">Disclaimer</a><a href="${link("/data-deletion")}">Data Deletion</a><a href="${link("/app-support")}">App Support</a></div></div><div class="shell fineprint"><span>© ${new Date().getFullYear()} Ventro Bank</span><span>Ventro Bank is fictional and does not provide real banking or financial services.</span></div></footer>`}

function layout(content){root.innerHTML=header()+`<main>${content}</main>`+footer();}

function pageHead(kicker,title,text){return `<div class="page-head"><div class="eyebrow">${kicker}</div><h1 class="page-title">${title}</h1><p class="lead">${text}</p></div>`}

function home(){layout(`<section class="shell hero"><div><div class="eyebrow">FICTIONAL · LARP · ENTERTAINMENT</div><h1>VENTRO <span>BANK</span></h1><h2>${SITE.tagline}</h2><p>A premium fictional banking simulator designed for LARP, roleplay, and entertainment. Build your fictional financial world without real money, deposits, transfers, or banking services.</p><div class="actions"><a class="btn primary" href="${SITE.androidPlayUrl || '#android'}">DOWNLOAD FOR ANDROID ↗</a><a class="btn secondary" href="#ios" onclick="return false">iOS COMING SOON</a><a class="btn secondary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN DISCORD ↗</a></div></div><div class="phone-wrap"><div class="phone"><div class="screen"><div class="mini-brand">VENTRO / PRIVATE VAULT</div><div class="balance"><small>FICTIONAL BALANCE</small><strong>$2,840,500</strong><small>+ 4.8% this cycle</small></div><div class="metric-row"><div class="metric"><small>NET WORTH</small><b>$3.18M</b></div><div class="metric"><small>VAULT</small><b>LV. 08</b></div></div><div class="balance"><small>RECENT ACTIVITY</small><div class="metric-row"><div class="metric"><b>+$85,000</b><small>ROLEPLAY INCOME</small></div><div class="metric"><b>-$42,500</b><small>LUXURY SPEND</small></div></div></div></div></div></div></section><section class="section alt"><div class="shell"><div class="section-head"><div><div class="eyebrow">SYSTEM OVERVIEW</div><h2>Everything in one vault.</h2></div><a class="btn secondary" href="${link("/features")}">VIEW FEATURES</a></div><div class="grid">${features.slice(0,6).map(f=>`<article class="card"><div class="num">${f[0]}</div><h3>${f[1]}</h3><p>${f[2]}</p></article>`).join("")}</div></div></section><section class="section"><div class="shell"><div class="cta"><div class="eyebrow">JOIN THE COMMUNITY</div><h2>Build your fictional financial world.</h2><p class="lead">Get announcements, support, updates, and community discussion through the official Ventro Bank Discord.</p><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN THE VENTRO BANK DISCORD ↗</a></div></div></section>`);}

function featuresPage(){layout(`<section class="page shell">${pageHead("VENTRO SYSTEMS","Built for fictional finance.","Explore the simulator systems that make Ventro Bank a structured LARP and roleplay experience.")}<div class="grid">${features.map(f=>`<article class="card"><div class="num">${f[0]}</div><div class="feature-icon">◈</div><h3>${f[1]}</h3><p>${f[2]}</p></article>`).join("")}</div></section>`);}

function appPage(){layout(`<section class="page shell">${pageHead("THE APP","Your fictional vault.","A premium mobile-first simulator interface for fictional balances, assets, transactions, achievements, and roleplay.")}<div class="showcase">${["Dashboard","Transactions","Vault","Statistics","Profile","Achievements"].map((x,i)=>`<figure class="shot"><div class="shot-screen"><div><strong>VENTRO BANK</strong><br>SECURE / FICTIONAL</div><div>MODULE <strong>0${i+1}</strong></div><div>STATUS <strong>ONLINE</strong></div><div>VAULT DATA · LOCAL SIMULATION</div></div><figcaption>${x}</figcaption></figure>`).join("")}</div><div class="notice"><strong>Asset-ready architecture.</strong> These showcase panels are local placeholders and can be replaced with final app screenshots without changing the page structure.</div></section>`);}

function updates(){layout(`<section class="page shell">${pageHead("UPDATES","Product updates.","A simple public changelog for Ventro Bank. Release details can be expanded as the product evolves.")}<div class="list"><div class="row"><span class="check">●</span><div><strong>Independent website architecture</strong><br><span class="muted">Static, GitHub Pages-ready website with no Base44 runtime dependency.</span></div></div><div class="row"><span class="check">●</span><div><strong>Public support and legal pages</strong><br><span class="muted">Support, privacy, terms, disclaimer, data deletion, and app support routes are available without login.</span></div></div><div class="row"><span class="check">●</span><div><strong>Responsive mobile experience</strong><br><span class="muted">Designed for phones, tablets, laptops, and large displays.</span></div></div></div></section>`);}

function community(){layout(`<section class="page shell">${pageHead("OFFICIAL COMMUNITY","Enter the Ventro vault.","Announcements, technical help, bug reports, and community discussion are handled through the official Discord.")}<div class="cta"><div class="status">OFFICIAL DISCORD</div><h2>Ventro Bank Community</h2><p class="lead">Join the official community for Ventro Bank support and updates.</p><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN DISCORD ↗</a></div></section>`);}

function faq(){layout(`<section class="page shell">${pageHead("FAQ","Frequently asked questions.","Straight answers about what Ventro Bank is and what the website does.")}<div class="faq"><details open><summary>Is Ventro Bank a real bank?</summary><p>No. Ventro Bank is a fictional banking simulator for LARP, roleplay, and entertainment.</p></details><details><summary>Does Ventro Bank handle real money?</summary><p>No. The simulator does not provide real deposits, withdrawals, transfers, payment processing, or financial services.</p></details><details><summary>Does the website have accounts or login?</summary><p>The public website does not operate a user account database or real authentication system.</p></details><details><summary>Where do I get support?</summary><p>Support, bug reports, and technical assistance are handled through the official Discord community.</p></details><details><summary>Is iOS available?</summary><p>iOS is currently marked as coming soon. The status can be updated centrally when availability changes.</p></details></div></section>`);}

function support(){layout(`<section class="page shell">${pageHead("SUPPORT","Need help with Ventro Bank?","All Ventro Bank support, technical assistance, bug reports, and help are handled through our official Discord community.")}<div class="cta"><h2>Official support channel</h2><p class="lead">There is no support form on this website. Join the Discord community and use the appropriate support channel.</p><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN THE VENTRO BANK DISCORD ↗</a></div></section>`);}

function accountPage(type){const title=type==="login"?"Website login":"Website signup";layout(`<section class="page shell">${pageHead("PUBLIC WEBSITE","Account access is not enabled.","The public Ventro Bank website does not operate a user account database, so there is no website login or signup form.")}<div class="notice"><strong>No fake authentication.</strong><p class="muted">This page intentionally does not collect passwords, emails, payment details, or other account credentials. Ventro Bank's public site remains a static information and download hub.</p></div><div class="mini-nav"><a href="${link("/app")}">Explore the App</a><a href="${link("/support")}">Get Support</a><a href="${link("/community")}">Join Discord</a></div></section>`);}

function legal(title,kicker,body){layout(`<section class="page shell legal">${pageHead(kicker,title,"Last Updated: September 25, 2026")}<div class="notice">Ventro Bank is a fictional banking simulator designed for LARP, roleplay, and entertainment. It is not a bank and does not provide real banking or financial services.</div>${body}</section>`);}

function legalPrivacy(){legal("Privacy Policy","LEGAL",`<h2>Website</h2><p>This public website is designed as a static information and product site. It does not provide a website account system, payment checkout, support form, or account database.</p><h2>Information submitted to us</h2><p>The website does not include forms that ask visitors to submit names, email addresses, financial credentials, government identification, or payment information.</p><h2>Third-party services</h2><p>Links may send you to third-party services such as Google Play or Discord. Those services operate under their own privacy policies and terms.</p><h2>Fictional app data</h2><p>Ventro Bank's fictional simulator features are not real banking records. Do not enter real financial credentials, banking information, government identifiers, or other sensitive information into a fictional roleplay experience.</p>`);}

function legalTerms(){legal("Terms of Use","LEGAL",`<h2>Use of the service</h2><p>Ventro Bank is provided for fictional LARP, roleplay, and entertainment purposes. You may not represent the simulator as a real bank or financial institution.</p><h2>No financial services</h2><p>Ventro Bank does not provide deposits, withdrawals, transfers, lending, investment management, payment processing, or other real financial services.</p><h2>No real-money value</h2><p>Balances, assets, transactions, achievements, and other values shown by the simulator are fictional and have no monetary value.</p><h2>Third-party links</h2><p>External services linked from the website are controlled by their respective providers.</p>`);}

function legalDisclaimer(){legal("Disclaimer","LEGAL",`<h2>Fictional product</h2><p>Ventro Bank is a fictional banking simulator created for LARP, roleplay, and entertainment.</p><h2>Not a bank</h2><p>Ventro Bank is not a bank, credit union, payment provider, financial institution, or financial advisory service.</p><h2>No real money</h2><p>Ventro Bank does not handle real money and does not support real deposits, withdrawals, transfers, or banking credentials.</p><h2>Use appropriate caution</h2><p>Do not use fictional simulator values as evidence of real financial status, account balances, assets, or transactions.</p>`);}

function dataDeletion(){legal("Data Deletion","LEGAL",`<h2>Website data</h2><p>The public website does not maintain a user account database or website profile system, so there is no website account record to delete through a web form.</p><h2>App data</h2><p>If you are referring to locally stored fictional simulator data in the app, use the app's available local-data controls or the device's app storage controls. Fictional simulator data is not a real bank record.</p><h2>Need help?</h2><p>For questions about deletion or app behavior, contact the official support community through Discord.</p><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">CONTACT SUPPORT ON DISCORD ↗</a>`);}

function appSupport(){layout(`<section class="page shell">${pageHead("GOOGLE PLAY SUPPORT","Ventro Bank app support.","For technical assistance, bug reports, and help with the Ventro Bank app, use the official Discord community.")}<div class="notice"><strong>Support channel:</strong><p class="muted">All Ventro Bank support, technical assistance, bug reports, and help are handled through our official Discord community.</p></div><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN THE VENTRO BANK DISCORD ↗</a></section>`);}

const routes={"/":home,"/features":featuresPage,"/app":appPage,"/updates":updates,"/community":community,"/faq":faq,"/support":support,"/login":()=>accountPage("login"),"/signup":()=>accountPage("signup"),"/account":()=>accountPage("account"),"/privacy":legalPrivacy,"/terms":legalTerms,"/disclaimer":legalDisclaimer,"/data-deletion":dataDeletion,"/app-support":appSupport};
(routes[path]||home)();
