import { SITE } from "./config.js";

const root=document.getElementById("app");
const base=location.pathname.startsWith("/Ventro-Bank-Website")?"/Ventro-Bank-Website":"";
const path=(location.pathname.startsWith(base)?location.pathname.slice(base.length):location.pathname).replace(/\/$/,"")||"/";
const link=p=>base+(p==="/"?"/":p);
const logo=`${base}/assets/ventro-mark.svg`;
const preview=`${base}/assets/app-preview.svg`;
const features=[
["01","FICTIONAL BALANCE","Track a custom fictional balance inside the simulator."],["02","EARN","Add roleplay income and build your fictional financial story."],["03","SPEND","Generate fictional purchases across luxury categories."],["04","TRANSACTION HISTORY","Review generated activity in a structured history."],["05","NET WORTH","Combine your fictional balance and assets."],["06","LUXURY ASSETS","Collect cars, watches, jewelry, homes, yachts and more."],["07","VAULT","Progress through vault levels and milestones."],["08","ACHIEVEMENTS","Unlock simulator achievements as you play."],["09","STATISTICS","View fictional financial activity at a glance."],["10","PROFILE","Customize your in-app identity and presentation."],["11","CUSTOMIZATION","Tune the presentation of your Ventro experience."],["12","NOTIFICATIONS","Stay informed about simulator activity and milestones."],["13","LARP ROLEPLAY","Built for fictional banking scenarios and entertainment."]];
function header(){return `<div class="topline"></div><header><div class="shell nav"><a class="brand" href="${link("/")}"><img src="${logo}" alt="Ventro Bank"><span>VENTRO BANK</span></a><button class="mobile-menu" aria-label="Open menu" onclick="document.querySelector('.navlinks').classList.toggle('open')">MENU</button><nav class="navlinks">${[["/features","FEATURES"],["/app","APP"],["/updates","UPDATES"],["/community","COMMUNITY"],["/faq","FAQ"],["/support","SUPPORT"],["/privacy","PRIVACY"]].map(([p,t])=>`<a href="${link(p)}">${t}</a>`).join("")}</nav></div></header>`}
function footer(){return `<footer><div class="shell footer-grid"><div><div class="brand"><img src="${logo}" alt="Ventro Bank"><span>VENTRO BANK</span></div><p class="muted">${SITE.tagline}</p><span class="status">FICTIONAL · LARP</span></div><div><div class="footer-title">Product</div><a href="${link("/features")}">Features</a><a href="${link("/app")}">App</a><a href="${link("/updates")}">Updates</a></div><div><div class="footer-title">Community</div><a href="${link("/community")}">Community</a><a href="${SITE.discordUrl}" target="_blank" rel="noopener">Discord</a><a href="${link("/support")}">Support</a><a href="${link("/faq")}">FAQ</a></div><div><div class="footer-title">Legal</div><a href="${link("/privacy")}">Privacy Policy</a><a href="${link("/terms")}">Terms</a><a href="${link("/disclaimer")}">Disclaimer</a><a href="${link("/data-deletion")}">Data Deletion</a><a href="${link("/app-support")}">App Support</a></div></div><div class="shell fineprint"><span>© ${new Date().getFullYear()} Ventro Bank</span><span>Ventro Bank is a fictional banking simulator designed for LARP, roleplay, and entertainment. It does not provide real banking or financial services.</span></div></footer>`}
function layout(content){root.innerHTML=header()+`<main>${content}</main>`+footer();window.scrollTo(0,0)}
function head(k,t,d){return `<div class="page-head"><div class="eyebrow">${k}</div><h1 class="page-title">${t}</h1><p class="lead">${d}</p></div>`}
function home(){layout(`<section class="shell hero"><div><div class="eyebrow">FICTIONAL · LARP · ENTERTAINMENT</div><h1>VENTRO <span>BANK</span></h1><h2>${SITE.tagline}</h2><p>A premium fictional banking simulator designed for LARP, roleplay, and entertainment. Build your fictional financial world without real money, deposits, transfers, or banking services.</p><div class="actions"><a class="btn primary" href="${SITE.androidPlayUrl||link("/app")}">DOWNLOAD FOR ANDROID ↗</a><a class="btn secondary" href="#ios">iOS COMING SOON</a><a class="btn secondary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN DISCORD ↗</a></div></div><div class="phone-wrap"><div class="phone"><img class="screen-image" src="${preview}" alt="Ventro Bank app dashboard"></div></div></section><section class="section alt"><div class="shell"><div class="section-head"><div><div class="eyebrow">SYSTEM OVERVIEW</div><h2>Everything in one vault.</h2></div><a class="btn secondary" href="${link("/features")}">VIEW FEATURES</a></div><div class="grid">${features.slice(0,6).map(f=>`<article class="card"><div class="num">${f[0]}</div><h3>${f[1]}</h3><p>${f[2]}</p></article>`).join("")}</div></div></section><section class="section"><div class="shell"><div class="cta"><div class="eyebrow">JOIN THE COMMUNITY</div><h2>Build your fictional financial world.</h2><p class="lead">Get announcements, support, updates, and community discussion through the official Ventro Bank Discord.</p><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN THE VENTRO BANK DISCORD ↗</a></div></div></section>`)}
function featuresPage(){layout(`<section class="page shell">${head("VENTRO SYSTEMS","Built for fictional finance.","Explore the simulator systems that make Ventro Bank a structured LARP and roleplay experience.")}<div class="grid">${features.map(f=>`<article class="card"><div class="num">${f[0]}</div><div class="feature-icon">◈</div><h3>${f[1]}</h3><p>${f[2]}</p></article>`).join("")}</div></section>`)}
function appPage(){layout(`<section class="page shell">${head("THE APP","Your fictional vault.","A premium mobile-first simulator interface for fictional balances, assets, transactions, achievements, and roleplay.")}<div class="showcase">${["Dashboard","Transactions","Vault","Statistics","Profile","Achievements"].map((x,i)=>`<figure class="shot"><div class="shot-screen"><img src="${preview}" alt="Ventro Bank ${x} app preview"></div><figcaption>${x}</figcaption></figure>`).join("")}</div><div class="notice"><strong>Current app preview.</strong> The supplied Ventro Bank dashboard artwork is now used as the live local website asset. Additional real screenshots can be added later.</div></section>`)}
function updates(){layout(`<section class="page shell">${head("UPDATES","Product updates.","A public changelog for Ventro Bank.")}<div class="list"><div class="row"><span class="check">●</span><div><strong>Independent website architecture</strong><br><span class="muted">Static GitHub Pages-ready website with no Base44 runtime dependency.</span></div></div><div class="row"><span class="check">●</span><div><strong>Public support and legal pages</strong><br><span class="muted">Support, privacy, terms, disclaimer, data deletion, and app support are publicly accessible.</span></div></div><div class="row"><span class="check">●</span><div><strong>Ventro Bank app branding</strong><br><span class="muted">Updated website logo and app preview.</span></div></div></div></section>`)}
function community(){layout(`<section class="page shell">${head("OFFICIAL COMMUNITY","Enter the Ventro vault.","Announcements, technical help, bug reports, and community discussion are handled through the official Discord.")}<div class="cta"><div class="status">OFFICIAL DISCORD</div><h2>Ventro Bank Community</h2><p class="lead">Join the official community for Ventro Bank support and updates.</p><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN DISCORD ↗</a></div></section>`)}
function faq(){layout(`<section class="page shell">${head("FAQ","Frequently asked questions.","Straight answers about what Ventro Bank is and what the website does.")}<div class="faq"><details open><summary>Is Ventro Bank a real bank?</summary><p>No. Ventro Bank is a fictional banking simulator for LARP, roleplay, and entertainment.</p></details><details><summary>Does Ventro Bank handle real money?</summary><p>No. It does not provide real deposits, withdrawals, transfers, payment processing, or financial services.</p></details><details><summary>Does the website have accounts or login?</summary><p>No. The public website does not operate a user account database or real authentication system.</p></details><details><summary>Where do I get support?</summary><p>Support, bug reports, and technical assistance are handled through the official Discord community.</p></details></div></section>`)}
function support(){layout(`<section class="page shell">${head("SUPPORT","Need help with Ventro Bank?","All Ventro Bank support, technical assistance, bug reports, and help are handled through our official Discord community.")}<div class="cta"><h2>Official support channel</h2><p class="lead">There is no support form on this website. Join the Discord community and use the appropriate support channel.</p><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN THE VENTRO BANK DISCORD ↗</a></div></section>`)}
function accountPage(){layout(`<section class="page shell">${head("PUBLIC WEBSITE","Account access is not enabled.","The public Ventro Bank website does not operate a user account database, so there is no website login or signup form.")}<div class="notice"><strong>No fake authentication.</strong><p class="muted">This page intentionally does not collect passwords, emails, payment details, or other account credentials.</p></div><div class="mini-nav"><a href="${link("/app")}">Explore the App</a><a href="${link("/support")}">Get Support</a><a href="${link("/community")}">Join Discord</a></div></section>`)}
function legal(t,b){layout(`<section class="page shell legal">${head("LEGAL",t,"Last Updated: September 25, 2026")}<div class="notice">Ventro Bank is a fictional banking simulator designed for LARP, roleplay, and entertainment. It is not a bank and does not provide real banking or financial services.</div>${b}</section>`)}
function privacy(){legal("Privacy Policy",`<h2>Website</h2><p>This public website is a static information and product site. It does not provide a website account system, payment checkout, support form, or account database.</p><h2>Information submitted to us</h2><p>The website does not include forms that ask visitors to submit names, email addresses, financial credentials, government identification, or payment information.</p><h2>Third-party services</h2><p>Links may send you to services such as Google Play or Discord. Those services operate under their own privacy policies.</p><h2>Fictional app data</h2><p>Ventro Bank simulator values are not real banking records. Do not enter real financial credentials, banking information, government identifiers, or other sensitive information into a fictional roleplay experience.</p>`)}
function terms(){legal("Terms of Use",`<h2>Use</h2><p>Ventro Bank is provided for fictional LARP, roleplay, and entertainment purposes. It must not be represented as a real bank or financial institution.</p><h2>No financial services</h2><p>Ventro Bank does not provide deposits, withdrawals, transfers, lending, investment management, payment processing, or other real financial services.</p><h2>No real-money value</h2><p>Balances, assets, transactions, achievements, and other values are fictional and have no monetary value.</p>`)}
function disclaimer(){legal("Disclaimer",`<h2>Fictional product</h2><p>Ventro Bank is a fictional banking simulator created for LARP, roleplay, and entertainment.</p><h2>Not a bank</h2><p>It is not a bank, credit union, payment provider, financial institution, or financial advisory service.</p><h2>No real money</h2><p>Ventro Bank does not handle real money and does not support real deposits, withdrawals, transfers, or banking credentials.</p>`)}
function deletion(){legal("Data Deletion",`<h2>Website data</h2><p>The public website does not maintain a user account database or website profile system.</p><h2>App data</h2><p>For locally stored fictional simulator data, use the app's available local-data controls or the device's app storage controls.</p><h2>Need help?</h2><p>For deletion questions or app behavior, contact the official support community through Discord.</p><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">CONTACT SUPPORT ON DISCORD ↗</a>`)}
function appSupport(){layout(`<section class="page shell">${head("GOOGLE PLAY SUPPORT","Ventro Bank app support.","For technical assistance, bug reports, and help with the Ventro Bank app, use the official Discord community.")}<div class="notice"><strong>Support channel:</strong><p class="muted">All Ventro Bank support, technical assistance, bug reports, and help are handled through our official Discord community.</p></div><a class="btn primary" href="${SITE.discordUrl}" target="_blank" rel="noopener">JOIN THE VENTRO BANK DISCORD ↗</a></section>`)}
const routes={"/":home,"/features":featuresPage,"/app":appPage,"/updates":updates,"/community":community,"/faq":faq,"/support":support,"/login":accountPage,"/signup":accountPage,"/account":accountPage,"/privacy":privacy,"/terms":terms,"/disclaimer":disclaimer,"/data-deletion":deletion,"/app-support":appSupport};
(routes[path]||home)();
