const enc=new TextEncoder();const now=()=>new Date().toISOString();const uid=()=>crypto.randomUUID();
const out=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json; charset=utf-8",...h}});
const cors=e=>({"access-control-allow-origin":e.FRONTEND_ORIGIN,"access-control-allow-credentials":"true","access-control-allow-headers":"content-type","access-control-allow-methods":"GET,POST,OPTIONS",vary:"Origin"});
const wrap=(r,e)=>{const h=new Headers(r.headers);for(const[k,v]of Object.entries(cors(e)))h.set(k,v);return new Response(r.body,{status:r.status,headers:h})};
const setCookie=(v,max)=>`ventro_session=${encodeURIComponent(v)}; Max-Age=${max}; Path=/; HttpOnly; Secure; SameSite=Lax`;
function cookie(req){const x=req.headers.get("Cookie")||"";const m=x.match(/(?:^|; )ventro_session=([^;]+)/);return m?decodeURIComponent(m[1]):null}
async function sha(s){return [...new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(s)))].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function passHash(p,s=crypto.randomUUID()){const k=await crypto.subtle.importKey("raw",enc.encode(p),"PBKDF2",false,["deriveBits"]);const b=await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(s),iterations:210000,hash:"SHA-256"},k,256);return `pbkdf2$210000$${s}$${btoa(String.fromCharCode(...new Uint8Array(b)))}`}
async function passOk(p,v){const[,it,salt,want]=v.split("$");const k=await crypto.subtle.importKey("raw",enc.encode(p),"PBKDF2",false,["deriveBits"]);const b=await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(salt),iterations:Number(it),hash:"SHA-256"},k,256);return btoa(String.fromCharCode(...new Uint8Array(b)))===want}
async function user(req,e){const sid=cookie(req);if(!sid)return null;return await e.DB.prepare("SELECT u.id,u.email,u.role,u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?").bind(sid,now()).first()}
async function auth(req,e){const u=await user(req,e);if(!u)throw new Error("UNAUTHENTICATED");return u}
async function admin(req,e){const u=await auth(req,e);if(u.role!=="admin")throw new Error("FORBIDDEN");return u}
async function stripe(e,path,params){const r=await fetch(`https://api.stripe.com/v1/${path}`,{method:"POST",headers:{Authorization:`Bearer ${e.STRIPE_SECRET_KEY}`,"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams(params)});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"Stripe request failed");return d}
async function sig(req,body,secret){const h=req.headers.get("Stripe-Signature");if(!h)return false;const a=Object.fromEntries(h.split(",").map(x=>x.split("=")));const t=Number(a.t);if(!t||Math.abs(Date.now()/1000-t)>300||!a.v1)return false;const k=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const b=await crypto.subtle.sign("HMAC",k,enc.encode(`${t}.${body}`));const hex=[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");return hex===a.v1}
async function email(e,to,subject,html){if(!e.RESEND_API_KEY)throw new Error("RESEND_API_KEY is not configured");const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${e.RESEND_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({from:e.EMAIL_FROM,to:[to],subject,html})});if(!r.ok)throw new Error("Email provider request failed")}
async function route(req,e){const u=new URL(req.url),p=u.pathname.replace(/\/$/,"")||"/";if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(e)});if(p==="/health")return out({ok:true});
if(p==="/auth/signup"&&req.method==="POST"){const b=await req.json(),em=String(b.email||"").trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(em)||String(b.password||"").length<10)return out({error:"Use a valid email and a password of at least 10 characters."},400);if(await e.DB.prepare("SELECT id FROM users WHERE email=?").bind(em).first())return out({error:"An account already exists for this email."},409);const id=uid(),t=now(),role=em===String(e.ADMIN_EMAIL).toLowerCase()?"admin":"user";await e.DB.prepare("INSERT INTO users(id,email,password_hash,role,created_at,updated_at) VALUES(?,?,?,?,?,?)").bind(id,em,await passHash(b.password),role,t,t).run();const sid=uid();await e.DB.prepare("INSERT INTO sessions(id,user_id,expires_at,created_at) VALUES(?,?,?,?)").bind(sid,id,new Date(Date.now()+30*864e5).toISOString(),t).run();return out({user:{id,email:em,role}},201,{"set-cookie":setCookie(sid,30*86400)})}
if(p==="/auth/login"&&req.method==="POST"){const b=await req.json(),em=String(b.email||"").trim().toLowerCase(),u=await e.DB.prepare("SELECT * FROM users WHERE email=?").bind(em).first();if(!u||!(await passOk(String(b.password||""),u.password_hash)))return out({error:"Invalid email or password."},401);const role=em===String(e.ADMIN_EMAIL).toLowerCase()?"admin":u.role;if(role!==u.role)await e.DB.prepare("UPDATE users SET role=?,updated_at=? WHERE id=?").bind(role,now(),u.id).run();const sid=uid();await e.DB.prepare("INSERT INTO sessions(id,user_id,expires_at,created_at) VALUES(?,?,?,?)").bind(sid,u.id,new Date(Date.now()+30*864e5).toISOString(),now()).run();return out({user:{id:u.id,email:u.email,role}},{"set-cookie":setCookie(sid,30*86400)})}
if(p==="/auth/logout"&&req.method==="POST"){const sid=cookie(req);if(sid)await e.DB.prepare("DELETE FROM sessions WHERE id=?").bind(sid).run();return out({ok:true},200,{"set-cookie":setCookie("",0)})}
if(p==="/auth/me")return out({user:await user(req,e)});
if(p==="/auth/forgot"&&req.method==="POST"){const b=await req.json(),u=await e.DB.prepare("SELECT id,email FROM users WHERE email=?").bind(String(b.email||"").trim().toLowerCase()).first();if(u){const token=uid()+uid(),h=await sha(token),t=now();await e.DB.prepare("INSERT INTO password_resets(id,user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)").bind(uid(),u.id,h,new Date(Date.now()+1800000).toISOString(),t).run();await email(e,u.email,"Reset your Ventro Bank password",`<p>Reset your password:</p><p><a href="${e.FRONTEND_ORIGIN}/reset-password?token=${encodeURIComponent(token)}">Reset password</a></p>`)}return out({ok:true})}
if(p==="/auth/reset"&&req.method==="POST"){const b=await req.json(),r=await e.DB.prepare("SELECT * FROM password_resets WHERE token_hash=? AND used_at IS NULL AND expires_at>?").bind(await sha(String(b.token||"")),now()).first();if(!r||String(b.password||"").length<10)return out({error:"Invalid or expired reset link."},400);await e.DB.prepare("UPDATE users SET password_hash=?,updated_at=? WHERE id=?").bind(await passHash(b.password),now(),r.user_id).run();await e.DB.prepare("UPDATE password_resets SET used_at=? WHERE id=?").bind(now(),r.id).run();await e.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(r.user_id).run();return out({ok:true})}
if(p==="/store")return out({product:"Ventro Bank",price_cad:10,configured:Boolean(e.STRIPE_PRICE_ID&&!e.STRIPE_PRICE_ID.startsWith("REPLACE"))});
if(p==="/stripe/checkout"&&req.method==="POST"){const u=await auth(req,e);if(!e.STRIPE_PRICE_ID||e.STRIPE_PRICE_ID.startsWith("REPLACE"))return out({error:"Stripe purchase is not configured yet."},503);const s=await stripe(e,"checkout/sessions",{mode:"payment","line_items[0][price]":e.STRIPE_PRICE_ID,"line_items[0][quantity]":"1",customer_email:u.email,client_reference_id:u.id,success_url:`${e.FRONTEND_ORIGIN}/account?purchase=success`,cancel_url:`${e.FRONTEND_ORIGIN}/store?purchase=cancelled`,"metadata[user_id]":u.id});return out({url:s.url})}
if(p==="/subscription/checkout"&&req.method==="POST"){const u=await auth(req,e);if(!e.STRIPE_SUBSCRIPTION_PRICE_ID||e.STRIPE_SUBSCRIPTION_PRICE_ID.startsWith("REPLACE"))return out({error:"Update subscription is not configured yet."},503);const s=await stripe(e,"checkout/sessions",{mode:"subscription","line_items[0][price]":e.STRIPE_SUBSCRIPTION_PRICE_ID,"line_items[0][quantity]":"1",customer_email:u.email,client_reference_id:u.id,success_url:`${e.FRONTEND_ORIGIN}/subscription`,cancel_url:`${e.FRONTEND_ORIGIN}/subscription?cancelled=1`,"metadata[user_id]":u.id});return out({url:s.url})}
if(p==="/subscription/portal"&&req.method==="POST"){const u=await auth(req,e),s0=await e.DB.prepare("SELECT stripe_customer_id FROM subscriptions WHERE user_id=? ORDER BY updated_at DESC LIMIT 1").bind(u.id).first();if(!s0?.stripe_customer_id)return out({error:"No Stripe customer is linked to this account."},404);const s=await stripe(e,"billing_portal/sessions",{customer:s0.stripe_customer_id,return_url:`${e.FRONTEND_ORIGIN}/subscription`});return out({url:s.url})}
if(p==="/account"){const u=await auth(req,e),purchase=await e.DB.prepare("SELECT * FROM purchases WHERE user_id=? AND status='paid' ORDER BY purchased_at DESC LIMIT 1").bind(u.id).first(),subscription=await e.DB.prepare("SELECT status,current_period_end FROM subscriptions WHERE user_id=? ORDER BY updated_at DESC LIMIT 1").bind(u.id).first(),latest=await e.DB.prepare("SELECT version,title,release_date FROM releases WHERE published=1 ORDER BY release_date DESC LIMIT 1").first();return out({user:u,purchase,subscription,latestRelease:latest})}
if(p==="/releases"){const u=await user(req,e),purchased=u?Boolean(await e.DB.prepare("SELECT id FROM purchases WHERE user_id=? AND status='paid' LIMIT 1").bind(u.id).first()):false,rows=await e.DB.prepare("SELECT id,version,title,release_date,release_notes,description FROM releases WHERE published=1 ORDER BY release_date DESC").all();return out({purchased,releases:rows.results})}
if(p.startsWith("/download/")&&req.method==="GET"){const u=await auth(req,e),paid=await e.DB.prepare("SELECT id FROM purchases WHERE user_id=? AND status='paid' LIMIT 1").bind(u.id).first();if(!paid)return out({error:"Purchase required."},403);const rel=await e.DB.prepare("SELECT * FROM releases WHERE id=? AND published=1").bind(p.split("/")[2]).first();if(!rel)return out({error:"Release not found."},404);const obj=await e.APK_BUCKET.get(rel.object_key);if(!obj)return out({error:"Release file unavailable."},404);const h=new Headers({"content-type":"application/vnd.android.package-archive", "content-disposition":`attachment; filename="Ventro-Bank-${rel.version}.apk"`,"cache-control":"private, no-store"});obj.writeHttpMetadata(h);return new Response(obj.body,{headers:h})}
if(p==="/updates"){const rows=await e.DB.prepare("SELECT id,title,version,published_at,description,release_notes,image_url,release_id FROM updates WHERE published=1 ORDER BY published_at DESC").all();return out({updates:rows.results})}
if(p==="/admin/overview"){await admin(req,e);const count=async q=>(await e.DB.prepare(q).first())?.n||0;return out({users:await count("SELECT COUNT(*) n FROM users"),purchases:await count("SELECT COUNT(*) n FROM purchases WHERE status='paid'"),activeSubscriptions:await count("SELECT COUNT(*) n FROM subscriptions WHERE status IN ('active','trialing')"),canceledSubscriptions:await count("SELECT COUNT(*) n FROM subscriptions WHERE status IN ('canceled','unpaid','past_due')"),latest:await e.DB.prepare("SELECT version,title FROM releases WHERE published=1 ORDER BY release_date DESC LIMIT 1").first()})}
if(p==="/admin/releases"&&req.method==="POST"){const a=await admin(req,e),f=await req.formData(),file=f.get("apk"),version=String(f.get("version")||"").trim(),title=String(f.get("title")||"").trim(),notes=String(f.get("release_notes")||"").trim(),description=String(f.get("description")||"").trim();if(!(file instanceof File)||!version||!title||!notes)return out({error:"Version, title, release notes, and APK are required."},400);const key=`releases/${version}/${uid()}.apk`;await e.APK_BUCKET.put(key,file.stream(),{httpMetadata:{contentType:"application/vnd.android.package-archive"}});const rid=uid(),t=now();await e.DB.prepare("INSERT INTO releases(id,version,title,release_date,release_notes,description,object_key,published,created_at) VALUES(?,?,?,?,?,?,?,1,?)").bind(rid,version,title,t,notes,description,key,t).run();return out({ok:true,id:rid,admin:a.email},201)}
if(p==="/admin/updates"&&req.method==="POST"){await admin(req,e);const b=await req.json(),id0=uid(),t=now();await e.DB.prepare("INSERT INTO updates(id,title,version,published_at,description,release_notes,image_url,release_id,published) VALUES(?,?,?,?,?,?,?,?,1)").bind(id0,b.title,b.version,t,b.description||"",b.release_notes||"",b.image_url||null,b.release_id||null).run();const us=await e.DB.prepare("SELECT u.id,u.email FROM users u JOIN subscriptions s ON s.user_id=u.id WHERE s.status IN ('active','trialing') GROUP BY u.id").all();for(const x of us.results){try{await email(e,x.email,`Ventro Bank ${b.version}: ${b.title}`,`<h2>${b.title}</h2><p>Version ${b.version}</p><p>${b.description||""}</p><p><a href="${e.FRONTEND_ORIGIN}/updates">View Update</a></p>`)}catch{}}return out({ok:true,id:id0},201)}
if(p==="/stripe/webhook"&&req.method==="POST"){const raw=await req.text();if(!(await sig(req,raw,e.STRIPE_WEBHOOK_SECRET)))return out({error:"Invalid signature."},400);const ev=JSON.parse(raw),o=ev.data?.object;if(ev.type==="checkout.session.completed"&&o.payment_status==="paid"){const userId=o.metadata?.user_id||o.client_reference_id;if(userId)await e.DB.prepare("INSERT OR IGNORE INTO purchases(id,user_id,stripe_session_id,stripe_payment_intent_id,amount,currency,status,purchased_at) VALUES(?,?,?,?,?,?,?,?)").bind(uid(),userId,o.id,o.payment_intent||null,o.amount_total||1000,o.currency||"cad","paid",now()).run()}if(ev.type.startsWith("customer.subscription.")){const userId=o.metadata?.user_id;if(userId)await e.DB.prepare("INSERT INTO subscriptions(id,user_id,stripe_customer_id,stripe_subscription_id,status,current_period_end,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(stripe_subscription_id) DO UPDATE SET status=excluded.status,current_period_end=excluded.current_period_end,updated_at=excluded.updated_at").bind(uid(),userId,o.customer,o.id,o.status,o.current_period_end?new Date(o.current_period_end*1000).toISOString():null,now()).run()}return out({received:true})}
return out({error:"Not found"},404)}
export default{async fetch(req,e){try{return wrap(await route(req,e),e)}catch(x){const s=x.message==="UNAUTHENTICATED"?401:x.message==="FORBIDDEN"?403:500;return wrap(out({error:s===500?"Server error":x.message},s),e)}}};
